### ISSUE TITLE
a small baseline to consider

### ISSUE THREAD

**Issue by jizongFox** [RayRuizhiLiao/demi_mi_estimator#1]
Hi @RayRuizhiLiao, 
Thanks for this great work. If I understand correctly, this paper uses a discriminator-style way to estimate the MI, which for me is very similar to Equ. 6 of https://arxiv.org/pdf/2007.10004.pdf. 
Any thought of adding this as a baseline to compare and discuss?

Best, 
Jizong

**Comment by jizongFox** [comment]
Sorry for asking again. What is the essential difference between your proposed method if $\alpha=0.5$ and the way used in Equ.  6 of my last comment and the JSD method in deep-infomax paper?

**Comment by rayruizhiliao** [comment]
Hi @jizongFox,

Once our (DEMI) estimator is trained, we only use the samples from the joint distribution to estimate its mutual information as shown in Eq. 11 in https://arxiv.org/pdf/2010.01766.pdf. In the paper you shared, samples from both the joint distribution and the product of marginals are used for mutual information estimation.

This is closely related to http://proceedings.mlr.press/v115/mukherjee20a/mukherjee20a.pdf, which we have compared and discussed in our paper.

Thank you and happy new year!

Best,
Ray

**Comment by jizongFox** [comment]
Thanks for your comments, I will have a look!
